//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTickr.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/2/search?jql=assignee=currentuser()")]
        public string Jira_GetTasks {
            get {
                return ((string)(this["Jira_GetTasks"]));
            }
            set {
                this["Jira_GetTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("assignee=currentuser() AND status NOT IN (STATUS_LIST)")]
        public string Jira_FilterQuery {
            get {
                return ((string)(this["Jira_FilterQuery"]));
            }
            set {
                this["Jira_FilterQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rest/api/2/search?jql=")]
        public string Jira_TaskSearchEndpoint {
            get {
                return ((string)(this["Jira_TaskSearchEndpoint"]));
            }
            set {
                this["Jira_TaskSearchEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rest/api/2/issue/TASK_ID/worklog")]
        public string Jira_LogTaskTime {
            get {
                return ((string)(this["Jira_LogTaskTime"]));
            }
            set {
                this["Jira_LogTaskTime"] = value;
            }
        }
    }
}
